INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Abasolo');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Acunia');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Allende');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Arteaga');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Candela');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Castanios');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Cuatro Cienegas');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Escobedo');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Francisco Madero');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Frontera');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('General Cepeda');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Guerrero');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Hidalgo');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Jimenez');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Juarez');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Lamadrid');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Matamoros');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Monclova');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Morelos');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Muzquiz');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Nadadores');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Nava');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Ocampo');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Parras');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Piedras Negras');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Progreso');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Ramos Arizpe');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Sabinas');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Sacramento');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Saltillo');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('San Buenaventura');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('San Juan de Sabinas');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('San Pedro');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Sierra Mojada');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Torreon');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Viesca');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Villa Union');
INSERT INTO `ticketsdb`.`municipio` (`nombre`) VALUES ('Zaragoza');

