INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Abasolo');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Acunia');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Allende');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Arteaga');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Candela');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Castanios');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Cuatro Cienegas');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Escobedo');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Francisco Madero');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Frontera');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('General Cepeda');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Guerrero');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Hidalgo');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Jimenez');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Juarez');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Lamadrid');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Matamoros');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Monclova');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Morelos');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Muzquiz');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Nadadores');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Nava');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Ocampo');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Parras');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Piedras Negras');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Progreso');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Ramos Arizpe');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Sabinas');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Sacramento');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Saltillo');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('San Buenaventura');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('San Juan de Sabinas');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('San Pedro');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Sierra Mojada');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Torreon');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Viesca');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Villa Union');
INSERT INTO `ticketsDB`.`municipio` (`nombremunicipio`) VALUES ('Zaragoza');

