-- MySQL Script generated by MySQL Workbench
-- Mon 27 Mar 2023 11:08:56 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketsdb` DEFAULT CHARACTER SET utf8 ;
USE `ticketsdb` ;

-- -----------------------------------------------------
-- Table `ticketsdb`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`alumno` (
  `curp` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `Paterno` VARCHAR(20) NOT NULL,
  `materno` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(20) NOT NULL,
  `asunto` VARCHAR(125) NOT NULL,
  `idmunicipio` INT NOT NULL,
  PRIMARY KEY (`curp`, `idmunicipio`),
  INDEX `fk_alumno_municipio_idx` (`idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `ticketsdb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`admin` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`turno` (
  `nturno` INT NOT NULL,
  `alumno_curp` VARCHAR(20) NOT NULL,
  `alumno_municipio_idmunicipio` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nturno`, `alumno_curp`, `alumno_municipio_idmunicipio`),
  INDEX `fk_turno_alumno1_idx` (`alumno_curp` ASC, `alumno_municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_turno_alumno1`
    FOREIGN KEY (`alumno_curp` , `alumno_municipio_idmunicipio`)
    REFERENCES `ticketsdb`.`alumno` (`curp` , `idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`municipio_has_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`municipio_has_turno` (
  `idmunicipio` INT NOT NULL,
  `nturno` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`, `nturno`),
  INDEX `fk_municipio_has_turno_turno1_idx` (`nturno` ASC) VISIBLE,
  INDEX `fk_municipio_has_turno_municipio1_idx` (`idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_has_turno_municipio1`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `ticketsdb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipio_has_turno_turno1`
    FOREIGN KEY (`nturno`)
    REFERENCES `ticketsdb`.`turno` (`nturno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
