-- MySQL Script generated by MySQL Workbench
-- Thu 30 Mar 2023 12:43:40 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketsdb` DEFAULT CHARACTER SET utf8 ;
USE `ticketsdb` ;

-- -----------------------------------------------------
-- Table `ticketsdb`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombremunicipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`alumno` (
  `curp` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `paterno` VARCHAR(20) NOT NULL,
  `materno` VARCHAR(20) NOT NULL,
  `edad` INT NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(12) NOT NULL,
  `asunto` VARCHAR(75) NOT NULL,
  `turno` INT NOT NULL DEFAULT 1,
  `status` VARCHAR(10) NOT NULL DEFAULT 'Pendiente',
  `idmunicipio` INT NOT NULL,
  PRIMARY KEY (`curp`, `idmunicipio`),
  INDEX `fk_alumno_municipio_idx` (`idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `ticketsdb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketsdb`.`admin` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
